### PR TITLE
Added functionality to delete empty output folders

### PR DESCRIPTION
**Pull request by JackLidge**
Hi Quinten,

This pull request adds some minor quality of life functionality that recently I've been wanting to add for our processing chain and was wondering if it might be beneficial to add it into the main acolite program.

I currently have several processing systems which are all using ACOLITE to process several thousand Sentinel-2 scenes, with the processing contained in a central PostgreSQL database. I haven't yet had time to extend the capabilities of this system to have a central data store (that is probably coming up soon), so I quite frequently run into the issue where an ACOLITE process is trying to run on a folder which isn't present locally. This then creates an output directory with just the process log file in it and currently each of the machines has a large number of these empty folders bar the log file in them.

This pull request is just a minor update to acolite/acolite/acolite_run.py, after the option to delete the log files, if the folder is empty and a new setting "delete_acolite_out_folder" is set to true, then it will also delete the empty folder newly created by ACOLITE. This is really only designed for the type of use case mentioned above, but I thought it might be good to have this functionality in the main acolite repo.

I've tested it, and it works for both deleting the empty directory and crucially, doesn't delete a directory when a successfully ACOLITE process has been completed.

Let me know if this is an appropriate pull request to add into ACOLITE, or if there are any further things I've missed which need editing.

Thanks,

Jack

### CODE REVIEW

**Comment by acolite** [comment]
Hi Jack

Thanks for the PR! I'm curious to hear more about your ACOLITE use case, but this can be via email as well. :-)

I guess by default the output folder / log files are there to show ACOLITE actually tried doing something. I added the text file deletion to reduce the number of files generated for large runs, usually with the same settings.

I am a bit wary of ACOLITE getting to delete stuff, but I see where you are coming from. There may be simpler solutions to the problem: Could you instead not run ACOLITE if the inputfile does not exist? Or, since it seems you are generating a unique output id for each run, could you not also use the same process to delete the output if empty? These options may not be possible if you are generating settings files first and then calling ACOLITE through "python launch_acolite.py --cli --settings" or similar, but it could be possible by running "ac.acolite.acolite_run(settings)" directly in Python with a settings dict.

The feature you add in the PR could also be implemented by the following, relying on os.rmdir() instead of on glob.glob() for the directory being empty:

```
## remove output directory if delete_acolite_output_directory is True and the directory is empty
try:
    if setu_l1r['delete_acolite_output_directory']:
        os.rmdir(setu_l1r['output']) 
except KeyError:
    print('Not testing output directory as "delete_acolite_output_directory" is not in settings.')
except OSError as err:
    print('Could not remove output directory {}'.format(setu_l1r['output']))
    if (err.errno == 66): print('Output directory not empty {}'.format(setu_l1r['output']))

```

Glob will ignore dotfiles by default, and may expand other symbols in the "output" path. (I don't know why you would, but it is possible to use asterisks or question marks in directory names.) This may cause either deletion of a folder with only hidden files through shutil.rmtree or non-deletion of an empty directory that glob matches to another non-empty directory. Also I have a slight preference for "directory" over "folder" but this doesn't really matter! :-)

Finally, I did not commit my .gitignore because I have more stuff in it. Not necessarily all secrets, so maybe I should include a .gitignore file in the repository...

Let me know what you think!

Quinten

**Comment by JackLidge** [comment]
Thanks for your quick and super in-depth reply!

Happy to expand a bit more about my current ACOLITE workflow in an email if you'd like, I'll send one over tomorrow.

You've raised a good point about the deletions, and a quick check to ensure the input folder isn't empty before running is probably the better way to go for my workflow and definitely possible as I'm running ACOLITE from within a python script, the same way as you mentioned above. 

Thanks for the heads up with os.rmdir(), I didn't know about those various nuances with glob and shutil. I didn't realise I'd committed the .gitignore to be honest, I'd only set it up in my copy so I could more clearly see what I'd edited without being lost in __pycache__'s.

So yes, I think a check before running ACOLITE is probably what I'll do now, happy to close this pull request without merging as it's not core ACOLITE functionality.

**Comment by acolite** [comment]
Hi Jack

I would be happy to hear about your projects using ACOLITE! 

Just so you know, I'm not really opposed to adding this option, but want to be careful about deleting stuff.  There are quite a few users and would not want to upset them. :-) Haven't tested yet on Windows either for example!

If the option defaults to False I guess we *should* be ok?  I can add the bit of code I posted above if that works for you?

Quinten

**Comment by JackLidge** [comment]
Yep it defaults to False so hopefully it will be alright to be added! The bit of code you posted above would work well for me!

**Comment by acolite** [comment]
I am testing this some more, and currently it only deletes the last level of the directory that was created. ACOLITE creates all the required levels of the output directory that don't exist. E.g. for /home/user/newfolder1/newfolder2 ACOLITE would create both folders, but only remove newfolder2. I will need to track the part of output that already existed before the run, perhaps like this:


```
sp = os.path.abspath(settings['output']).split(os.sep)
newpath = None
cp = ''
for l in sp:
    cp += l + os.sep
    if not os.path.exists(cp):
        newpath = cp        
        break
```

And then run through the path backwards up to "newpath" when deleting the directories.

Edit: added missing line in code

**Comment by JackLidge** [comment]
Ah I wasn't aware about the multiple levels created from ACOLITE, makes sense to employ your solution then where it finds all the newly created folders.

**Comment by acolite** [comment]
Well it depends on what you put as output path whether ACOLITE creates multiple levels. :-)

**Comment by acolite** [comment]
Hi Jack

I have added this functionality yesterday: https://github.com/acolite/acolite/commit/990744808d15abae089da999f479b4478233d8ee

I hope this is still useful! You can try it by setting delete_acolite_output_directory=True and delete_acolite_run_text_files=True

Quinten

**Comment by JackLidge** [comment]
Hi Quinten, sorry I thought I'd responded to this! Thanks very much for adding that in, it worked very nicely!

The branch closing and force-pushing was I think because I deleted my original fork and reforked it for the PYPI pull request, so ignore all the stuff about force pushing.

**Pull request closed without merging**
